import React from "react";

const fontsPath = "/fonts/";

export const onRenderBody = ({ setHeadComponents }) => {
    setHeadComponents([
        <link
            key="gothampro-woff"
            rel="preload"
            href={`${fontsPath}GothamPro.woff`}
            as="font"
            type="font/woff"
            crossOrigin="anonymous"
        />,
        <link
            key="gothampro-woff2"
            rel="preload"
            href={`${fontsPath}GothamPro.woff2`}
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
        />,
        <link
            key="gothampro-medium-woff2"
            rel="preload"
            href={`${fontsPath}GothamPro-Medium.woff2`}
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
        />,
        <link
            key="gothampro-medium-woff"
            rel="preload"
            href={`${fontsPath}GothamPro-Medium.woff`}
            as="font"
            type="font/woff"
            crossOrigin="anonymous"
        />,
        <link
            key="gothampro-bold-woff"
            rel="preload"
            href={`${fontsPath}GothamPro-Bold.woff`}
            as="font"
            type="font/woff"
            crossOrigin="anonymous"
        />,
        <link
            key="gothampro-bold-woff2"
            rel="preload"
            href={`${fontsPath}GothamPro-Bold.woff2`}
            as="font"
            type="font/woff2"
            crossOrigin="anonymous"
        />,
        <link
            key="slick.min.css"
            rel="stylesheet"
            type="text/css"
            charSet="UTF-8"
            href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css"
        />,
        <link
            key="slick-theme.min.css"
            rel="stylesheet"
            type="text/css"
            href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css"
        />,
    ]);
};
